#CS 30
#Owen Hipfner
#Starting Date 16 dec 2021
import list as lis
import os


####Version 4####
#Making website an object and giving it attributes that can be called on.
class Website():
    def __init__(
        self,
        name,
        description,
        url,
    ):
        self.name = name
        self.description = description
        self.url = url

#A way to remove the history file if the user quits the web browser
if os.path.exists("history.txt"):
    os.remove("history.txt")
else:
    print("The file doesn't exist")

#A small amount of instructions for the user
print("##PLEASE READ##")
print('''
Welcome to Bew, this is a webbrowser where you can search a variety of websites that you might use on the daily.''')
#A is a variable for the while loop.
a = 1
#A while loop to keep the websites avalible.
while a == 1:
    #Importing the title from a different file.
    lis.title()
    print("Use command 'help' if you need")
    #Input from the user so then it can.
    user_input = str(input("Search a website: "))
    print("\n")
    #If the user searches the name it will print the attributes.
    if user_input == "wikipedia":
        Wikipedia = Website("Wikipedia", "A site for information",
        "https://en.wikipedia.org/wiki/Main_Page")
        print(Wikipedia.name)
        print(Wikipedia.description)
        print(Wikipedia.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Wikipedia.name)
        f.write("\n")
        f.write(Wikipedia.url)
        f.write("\n")
        f.write("\n")
        f.close
    #Another possible object to search.
    elif user_input == "google":
        Google = Website("Google", "A competing web browser",
        "https://www.google.ca/")
        print(Google.name)
        print(Google.description)
        print(Google.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Google.name)
        f.write("\n")
        f.write(Google.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "youtube":
        Youtube = Website("Youtube", "Internet video site to entertain",
        "https://www.youtube.com/")
        print(Youtube.name)
        print(Youtube.description)
        print(Youtube.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Youtube.name)
        f.write("\n")
        f.write(Youtube.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "twitch":
        Twitch = Website("Twitch", "Live stream platform",
        "https://www.twitch.tv/")
        print(Twitch.name)
        print(Twitch.description)
        print(Twitch.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Twitch.name)
        f.write("\n")
        f.write(Twitch.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "amazon":
        Amazon = Website("Amazon", "Shopping site for all needs",
        "https://www.amazon.ca/")
        print(Amazon.name)
        print(Amazon.description)
        print(Amazon.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Amazon.name)
        f.write("\n")
        f.write(Amazon.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "netflix":
        Netflix = Website("Netflix", "Movie and tv streaming service",
        "https://www.netflix.com/ca/")
        print(Netflix.name)
        print(Netflix.description)
        print(Netflix.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Netflix.name)
        f.write("\n")
        f.write(Netflix.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "disney":
        Disney = Website("Disney","Has streaming app, parks to travel and movies",
        "https://www.disney.com/")
        print(Disney.name)
        print(Disney.description)
        print(Disney.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Disney.name)
        f.write("\n")
        f.write(Disney.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "best buy":
        Best_Buy = Website("Best Buy", "Electronic and tech store",
        "https://www.bestbuy.ca/en-ca")
        print(Best_Buy.name)
        print(Best_Buy.description)
        print(Best_Buy.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Best_Buy.name)
        f.write("\n")
        f.write(Best_Buy.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "bing":
        Bing = Website("Bing", "A competing web browser",
        "https://www.bing.com/")
        print(Bing.name)
        print(Bing.description)
        print(Bing.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Bing.name)
        f.write("\n")
        f.write(Bing.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "yahoo":
        Yahoo = Website("Yahoo", "A competing web browser",
        "https://ca.yahoo.com/")
        print(Yahoo.name)
        print(Yahoo.description)
        print(Yahoo.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Yahoo.name)
        f.write("\n")
        f.write(Yahoo.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "microsoft":
        Microsoft = Website("Microsoft", "Technology company", "https://www.microsoft.com/en-ca")
        print(Microsoft.name)
        print(Microsoft.description)
        print(Microsoft.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Microsoft.name)
        f.write("\n")
        f.write(Microsoft.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "hp":
        Hp = Website("Hp", "Technology company laptops, printers, etc...", "https://www.hp.com/ca-en/home.html")
        print(Hp.name)
        print(Hp.description)
        print(Hp.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Hp.name)
        f.write("\n")
        f.write(Hp.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "apple":
        Apple = Website("Apple", "Technology company Phones, tablets, etc...", "https://www.apple.com/ca/")
        print(Apple.name)
        print(Apple.description)
        print(Apple.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Apple.name)
        f.write("\n")
        f.write(Apple.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "duolingo":
        Duolingo = Website("Duolingo", "Language learning site", "https://www.duolingo.com/")
        print(Duolingo.name)
        print(Duolingo.description)
        print(Duolingo.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Duolingo.name)
        f.write("\n")
        f.write(Duolingo.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "samsung":
        Samsung = Website("Samsung", "Technology company Phones, tablets, etc...", "https://www.samsung.com/ca/")
        print(Samsung.name)
        print(Samsung.description)
        print(Samsung.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Samsung.name)
        f.write("\n")
        f.write(Samsung.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "vans":
        Vans = Website("Vans", "Shoe company", "https://www.vans.ca/en-ca")
        print(Vans.name)
        print(Vans.description)
        print(Vans.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Vans.name)
        f.write("\n")
        f.write(Vans.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "nike":
        Nike = Website("Nike", "Shoe company and clothes brand", "https://www.nike.com/ca/")
        print(Nike.name)
        print(Nike.description)
        print(Nike.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Nike.name)
        f.write("\n")
        f.write(Nike.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "addidas":
        Addidas = Website("Addidas", "Shoe company and clothes brand", "https://www.adidas.ca/en")
        print(Addidas.name)
        print(Addidas.description)
        print(Addidas.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Addidas.name)
        f.write("\n")
        f.write(Addidas.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "dell":
        Dell = Website("Dell", "Technology company laptops, Monitors, etc...", "https://www.dell.com/en-ca")
        print(Dell.name)
        print(Dell.description)
        print(Dell.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Dell.name)
        f.write("\n")
        f.write(Dell.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "sasktel":
        Sasktel = Website("Sasktel", "Cell phone service provider", "https://www.sasktel.com/store/browse/Personal/_/N-26v0")
        print(Sasktel.name)
        print(Sasktel.description)
        print(Sasktel.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Sasktel.name)
        f.write("\n")
        f.write(Sasktel.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "access":
        Access = Website("Access", "Telecommunications service provider", "https://www.myaccess.ca/")
        print(Access.name)
        print(Access.description)
        print(Access.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Access.name)
        f.write("\n")
        f.write(Access.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "replit":
        Replit = Website("Replit", "Coding company", "https://replit.com/~")
        print(Replit.name)
        print(Replit.description)
        print(Replit.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Replit.name)
        f.write("\n")
        f.write(Replit.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "github":
        Github = Website("Github", "Software developing company", "https://github.com/")
        print(Github.name)
        print(Github.description)
        print(Github.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Github.name)
        f.write("\n")
        f.write(Github.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "spell check plus":
        Spell_Check_Plus = Website("Spell Check Plus", "Grammar Checker and Spell Checker(english)", "https://spellcheckplus.com/en/")
        print(Spell_Check_Plus.name)
        print(Spell_Check_Plus.description)
        print(Spell_Check_Plus.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Spell_Check_Plus.name)
        f.write("\n")
        f.write(Spell_Check_Plus.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "bonpatron":
        Bonpatron = Website("Bonpatron", "Grammar Checker (french)", "https://bonpatron.com/en/")
        print(Bonpatron.name)
        print(Bonpatron.description)
        print(Bonpatron.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Bonpatron.name)
        f.write("\n")
        f.write(Bonpatron.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "linguee":
        Linguee = Website("Linguee", "Language Translator", "https://www.linguee.com/")
        print(Linguee.name)
        print(Linguee.description)
        print(Linguee.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Linguee.name)
        f.write("\n")
        f.write(Linguee.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "google classroom":
        Google_Classroom = Website("Google Classroom", "Learning platform", "https://classroom.google.com/")
        print(Google_Classroom.name)
        print(Google_Classroom.description)
        print(Google_Classroom.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Google_Classroom.name)
        f.write("\n")
        f.write(Google_Classroom.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "google slides":
        Google_Slides = Website("Google Slides", "Presentation program", "https://docs.google.com/presentation/")
        print(Google_Slides.name)
        print(Google_Slides.description)
        print(Google_Slides.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Google_Slides.name)
        f.write("\n")
        f.write(Google_Slides.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "google docs":
        Google_Docs = Website("Google Docs", "Online word processor and documentation", "https://docs.google.com/")
        print(Google_Docs.name)
        print(Google_Docs.description)
        print(Google_Docs.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Google_Docs.name)
        f.write("\n")
        f.write(Google_Docs.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "google drive":
        Google_Drive = Website("Google Drive", "File storage and sychronization service", "https://drive.google.com/drive/my-drive?ths=true")
        print(Google_Drive.name)
        print(Google_Drive.description)
        print(Google_Drive.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Google_Drive.name)
        f.write("\n")
        f.write(Google_Drive.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "gmail":
        Gmail = Website("Gmail", "Email service", "https://www.google.com/gmail/")
        print(Gmail.name)
        print(Gmail.description)
        print(Gmail.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Gmail.name)
        f.write("\n")
        f.write(Gmail.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "google maps":
        Google_Maps = Website("Google Maps", "Web mapping and route planning service", "https://maps.google.com/")
        print(Google_Maps.name)
        print(Google_Maps.description)
        print(Google_Maps.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Google_Maps.name)
        f.write("\n")
        f.write(Google_Maps.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "desmos":
        Desmos = Website("Desmos", "An advanced graphing calculator", "https://www.desmos.com/")
        print(Desmos.name)
        print(Desmos.description)
        print(Desmos.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Desmos.name)
        f.write("\n")
        f.write(Desmos.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "google translate":
        Google_Translate = Website("Google Translate", "Language Translator", "https://translate.google.ca/")
        print(Google_Translate.name)
        print(Google_Translate.description)
        print(Google_Translate.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Google_Translate.name)
        f.write("\n")
        f.write(Google_Translate.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "lego":
        Lego = Website("Lego", "Toy production company", "https://www.lego.com/en-ca")
        print(Lego.name)
        print(Lego.description)
        print(Lego.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Lego.name)
        f.write("\n")
        f.write(Lego.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "kahoot":
        Kahoot = Website("Kahoot", "Game based learning platform", "https://kahoot.com/")
        print(Kahoot.name)
        print(Kahoot.description)
        print(Kahoot.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Kahoot.name)
        f.write("\n")
        f.write(Kahoot.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "reverso context":
        Reverso_Context = Website("Reverso Context", "Language translator", "https://context.reverso.net/translation/")
        print(Reverso_Context.name)
        print(Reverso_Context.description)
        print(Reverso_Context.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Reverso_Context.name)
        f.write("\n")
        f.write(Reverso_Context.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "grammarly":
        Grammarly = Website("Grammarly", "Grammar Checker and spell checker(english)", "https://www.grammarly.com/")
        print(Grammarly.name)
        print(Grammarly.description)
        print(Grammarly.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Grammarly.name)
        f.write("\n")
        f.write(Grammarly.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "edsby":
        Edsby = Website("Edsby", "Learning platform", "https://edsby.rbe.sk.ca/students.html")
        print(Edsby.name)
        print(Edsby.description)
        print(Edsby.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Edsby.name)
        f.write("\n")
        f.write(Edsby.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "remind":
        Remind = Website("Remind", "Messaging platform", "https://www.remind.com/")
        print(Remind.name)
        print(Remind.description)
        print(Remind.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Remind.name)
        f.write("\n")
        f.write(Remind.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "myblueprint":
        MyBluePrint = Website("MyBluePrint", "Education technology company", "https://myblueprint.ca/")
        print(MyBluePrint.name)
        print(MyBluePrint.description)
        print(MyBluePrint.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(MyBluePrint.name)
        f.write("\n")
        f.write(MyBluePrint.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "oculus":
        Oculus = Website("Oculus", "VR technology company", "https://www.oculus.com/")
        print(Oculus.name)
        print(Oculus.description)
        print(Oculus.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Oculus.name)
        f.write("\n")
        f.write(Oculus.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "instagram":
        Instagram = Website("Instagram", "Social media service", "https://www.instagram.com/?hl=en")
        print(Instagram.name)
        print(Instagram.description)
        print(Instagram.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Instagram.name)
        f.write("\n")
        f.write(Instagram.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "snapchat":
        Snapchat = Website("Snapchat", "Social media service", "https://www.snapchat.com/")
        print(Snapchat.name)
        print(Snapchat.description)
        print(Snapchat.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Snapchat.name)
        f.write("\n")
        f.write(Snapchat.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "whatsapp":
        Whatsapp = Website("Whatsapp", "Messaging service", "https://www.whatsapp.com/")
        print(Whatsapp.name)
        print(Whatsapp.description)
        print(Whatsapp.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Whatsapp.name)
        f.write("\n")
        f.write(Whatsapp.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "xbox":
        Xbox = Website("Xbox", "Gaming company", "https://www.xbox.com/")
        print(Xbox.name)
        print(Xbox.description)
        print(Xbox.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Xbox.name)
        f.write("\n")
        f.write(Xbox.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "playstation":
        Playstation = Website("Playstation", "Gaming company", "https://www.playstation.com/en-ca/")
        print(Playstation.name)
        print(Playstation.description)
        print(Playstation.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Playstation.name)
        f.write("\n")
        f.write(Playstation.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "spotify":
        Spotify = Website("Spotify", "Music streaming service", "https://www.spotify.com/")
        print(Spotify.name)
        print(Spotify.description)
        print(Spotify.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Spotify.name)
        f.write("\n")
        f.write(Spotify.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "discord":
        Discord = Website("Discord", "Communication and messaging service", "https://discord.com/")
        print(Discord.name)
        print(Discord.description)
        print(Discord.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Discord.name)
        f.write("\n")
        f.write(Discord.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "tiktok":
        Tik_Tok = Website("TikTok", "Social media service", "https://www.tiktok.com/")
        print(Tik_Tok.name)
        print(Tik_Tok.description)
        print(Tik_Tok.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Tik_Tok.name)
        f.write("\n")
        f.write(Tik_Tok.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "skipthedishes":
        SkipTheDishes = Website("SkipTheDishes", "Food deliverie service", "https://www.skipthedishes.com/")
        print(SkipTheDishes.name)
        print(SkipTheDishes.description)
        print(SkipTheDishes.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(SkipTheDishes.name)
        f.write("\n")
        f.write(SkipTheDishes.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "doordash":
        DoorDash = Website("DoorDash", "Food deliverie service", "https://www.doordash.com/")
        print(DoorDash.name)
        print(DoorDash.description)
        print(DoorDash.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(DoorDash.name)
        f.write("\n")
        f.write(DoorDash.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "uber eats":
        Uber_Eats = Website("Uber Eats", "Food deliverie service", "https://www.ubereats.com/")
        print(Uber_Eats.name)
        print(Uber_Eats.description)
        print(Uber_Eats.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Uber_Eats.name)
        f.write("\n")
        f.write(Uber_Eats.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "uber":
        Uber = Website("Uber", "Transportation service", "https://www.uber.com/")
        print(Uber.name)
        print(Uber.description)
        print(Uber.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Uber.name)
        f.write("\n")
        f.write(Uber.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "macdonalds":
        Macdonalds = Website("Macdonalds", "Fast food restaurant company", "https://www.mcdonalds.com/ca/en-ca.html")
        print(Macdonalds.name)
        print(Macdonalds.description)
        print(Macdonalds.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Macdonalds.name)
        f.write("\n")
        f.write(Macdonalds.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "burger king":
        Burger_King = Website("Burger King", "Fast food restaurant company", "https://www.bk.com/")
        print(Burger_King.name)
        print(Burger_King.description)
        print(Burger_King.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Burger_King.name)
        f.write("\n")
        f.write(Burger_King.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "weather":
        Weather = Website("Weather", "Weather in your area", "https://www.theweathernetwork.com/")
        print(Weather.name)
        print(Weather.description)
        print(Weather.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Weather.name)
        f.write("\n")
        f.write(Weather.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "facebook":
        Facebook = Website("Facebook", "Social media service", "https://www.facebook.com/")
        print(Facebook.name)
        print(Facebook.description)
        print(Facebook.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Facebook.name)
        f.write("\n")
        f.write(Facebook.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "reddit":
        Reddit = Website("Reddit", "Social news service", "https://www.reddit.com/")
        print(Reddit.name)
        print(Reddit.description)
        print(Reddit.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Reddit.name)
        f.write("\n")
        f.write(Reddit.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "cbc":
        Cbc = Website("Cbc", "Social news service", "https://www.cbc.ca/")
        print(Cbc.name)
        print(Cbc.description)
        print(Cbc.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Cbc.name)
        f.write("\n")
        f.write(Cbc.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "global":
        Global = Website("Global", "Social news service", "https://globalnews.ca/")
        print(Global.name)
        print(Global.description)
        print(Global.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Global.name)
        f.write("\n")
        f.write(Global.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "ctv":
        Ctv = Website("Ctv", "Social news service", "https://www.ctvnews.ca/")
        print(Ctv.name)
        print(Ctv.description)
        print(Ctv.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Ctv.name)
        f.write("\n")
        f.write(Ctv.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "radio canada":
        Radio_Canada = Website("Radio Canada", "Social broadcasting service", "https://ici.radio-canada.ca/")
        print(Radio_Canada.name)
        print(Radio_Canada.description)
        print(Radio_Canada.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Radio_Canada.name)
        f.write("\n")
        f.write(Radio_Canada.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "soundcloud":
        SoundCloud = Website("Soundcloud", "Music streaming service", "https://soundcloud.com/")
        print(SoundCloud.name)
        print(SoundCloud.description)
        print(SoundCloud.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(SoundCloud.name)
        f.write("\n")
        f.write(SoundCloud.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "intel":
        Intel = Website("Intel", "Computer technology company", "https://www.intel.ca/content/www/ca/en/homepage.html")
        print(Intel.name)
        print(Intel.description)
        print(Intel.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Intel.name)
        f.write("\n")
        f.write(Intel.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "nvidia":
        Nvidia = Website("Nvidia", "Computer technology company", "https://www.nvidia.com/")
        print(Nvidia.name)
        print(Nvidia.description)
        print(Nvidia.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Nvidia.name)
        f.write("\n")
        f.write(Nvidia.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "amd":
        Amd = Website("Amd", "Computer technology company", "https://www.amd.com/en")
        print(Amd.name)
        print(Amd.description)
        print(Amd.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Amd.name)
        f.write("\n")
        f.write(Amd.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "hyperx":
        Hyperx = Website("Hyperx", "Gaming technology company", "https://www.hyperxgaming.com/en")
        print(Hyperx.name)
        print(Hyperx.description)
        print(Hyperx.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Hyperx.name)
        f.write("\n")
        f.write(Hyperx.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "corsair":
        Corsair = Website("Corsair", "Gaming technology company", "https://www.corsair.com/ca/en/")
        print(Corsair.name)
        print(Corsair.description)
        print(Corsair.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Corsair.name)
        f.write("\n")
        f.write(Corsair.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "newegg":
        Newegg = Website("Newegg", "Computer hardware retailer", "https://www.newegg.ca/")
        print(Newegg.name)
        print(Newegg.description)
        print(Newegg.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Newegg.name)
        f.write("\n")
        f.write(Newegg.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "prezi":
        Prezi = Website("Prezi", "Presentation program", "https://prezi.com/")
        print(Prezi.name)
        print(Prezi.description)
        print(Prezi.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Prezi.name)
        f.write("\n")
        f.write(Prezi.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "amazon prime":
        Amazon_Prime = Website("Amazon Prime", "Movie streaming service", "https://www.primevideo.com/")
        print(Amazon_Prime.name)
        print(Amazon_Prime.description)
        print(Amazon_Prime.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Amazon_Prime.name)
        f.write("\n")
        f.write(Amazon_Prime.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "pinterest":
        Pinterest = Website("Pinterest", "Social media service", "https://www.pinterest.com/")
        print(Pinterest.name)
        print(Pinterest.description)
        print(Pinterest.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Pinterest.name)
        f.write("\n")
        f.write(Pinterest.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "sephora":
        Sephora = Website("Sephora", "Beauty products and personal care", "https://www.sephora.com/")
        print(Sephora.name)
        print(Sephora.description)
        print(Sephora.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Sephora.name)
        f.write("\n")
        f.write(Sephora.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "american eagle":
        American_Eagle = Website("American Eagle", "Lifestyle and clothing brand", "https://www.ae.com/ca/en")
        print(American_Eagle.name)
        print(American_Eagle.description)
        print(American_Eagle.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(American_Eagle.name)
        f.write("\n")
        f.write(American_Eagle.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "urban outfitters":
        Urban_Outfitters = Website("Urban Outfitters", "Lifestyle and clothing brand", "https://www.urbanoutfitters.com/en-ca/")
        print(Urban_Outfitters.name)
        print(Urban_Outfitters.description)
        print(Urban_Outfitters.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Urban_Outfitters.name)
        f.write("\n")
        f.write(Urban_Outfitters.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "kijiji":
        Kijiji = Website("Kijiji", "Advertising website", "https://www.kijiji.ca/")
        print(Kijiji.name)
        print(Kijiji.description)
        print(Kijiji.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Kijiji.name)
        f.write("\n")
        f.write(Kijiji.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "starbucks":
        Starbucks = Website("Starbucks", "Coffeehouse", "https://www.starbucks.ca/")
        print(Starbucks.name)
        print(Starbucks.description)
        print(Starbucks.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Starbucks.name)
        f.write("\n")
        f.write(Starbucks.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "logitech":
        Logitech = Website("Logitech", "Computer hardware company", "https://www.logitech.com/?crid=7")
        print(Logitech.name)
        print(Logitech.description)
        print(Logitech.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Logitech.name)
        f.write("\n")
        f.write(Logitech.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "sport check":
        Sportchek = Website("Sport chek", "Sport clothing and sport equipement company", "https://www.sportchek.ca/")
        print(Sportchek.name)
        print(Sportchek.description)
        print(Sportchek.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Sportchek.name)
        f.write("\n")
        f.write(Sportchek.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "canadian tire":
        Canadian_Tire = Website("Canadian Tire", "Sport, automotive, and household company", "https://www.canadiantire.ca/en/en-1.html")
        print(Canadian_Tire.name)
        print(Canadian_Tire.description)
        print(Canadian_Tire.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Canadian_Tire.name)
        f.write("\n")
        f.write(Canadian_Tire.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "marks":
        Marks = Website("Marks", "Lifestyle and clothing brand", "https://www.marks.com/")
        print(Marks.name)
        print(Marks.description)
        print(Marks.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Marks.name)
        f.write("\n")
        f.write(Marks.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "razer":
        Razer = Website("Razer", "Gaming technology company", "https://www.razer.com/ca-en")
        print(Razer.name)
        print(Razer.description)
        print(Razer.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Razer.name)
        f.write("\n")
        f.write(Razer.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "astro":
        Astro = Website("Astro", "Gaming technology company", "https://www.astrogaming.com/en-ca")
        print(Astro.name)
        print(Astro.description)
        print(Astro.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Astro.name)
        f.write("\n")
        f.write(Astro.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "home depot":
        Home_Depot = Website("Home Depot", "Home improvement retailer", "https://www.homedepot.ca/en/home.html")
        print(Home_Depot.name)
        print(Home_Depot.description)
        print(Home_Depot.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Home_Depot.name)
        f.write("\n")
        f.write(Home_Depot.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "a&w":
        A_W = Website("A&W", "Fast food restaurant company", "https://web.aw.ca/")
        print(A_W.name)
        print(A_W.description)
        print(A_W.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(A_W.name)
        f.write("\n")
        f.write(A_W.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "urban dictionairy":
        Urban_Dictionairy = Website("Urban Dictionairy", "Dictionairy for slang words", "https://www.urbandictionary.com/")
        print(Urban_Dictionairy.name)
        print(Urban_Dictionairy.description)
        print(Urban_Dictionairy.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Urban_Dictionairy.name)
        f.write("\n")
        f.write(Urban_Dictionairy.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "costco":
        Costco = Website("Costco", "Wholesale corporation", "https://www.costco.ca/")
        print(Costco.name)
        print(Costco.description)
        print(Costco.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Costco.name)
        f.write("\n")
        f.write(Costco.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "lululemon":
        Lululemon = Website("Lululemon", "Lifestyle and clothing brand", "https://shop.lululemon.com/")
        print(Lululemon.name)
        print(Lululemon.description)
        print(Lululemon.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Lululemon.name)
        f.write("\n")
        f.write(Lululemon.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "london drugs":
        London_Drugs = Website("London Drugs", "Pharmacy retailer", "https://www.londondrugs.com/")
        print(London_Drugs.name)
        print(London_Drugs.description)
        print(London_Drugs.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(London_Drugs.name)
        f.write("\n")
        f.write(London_Drugs.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "otterbox":
        Otter_Box = Website("OtterBox", "Phone accessory company", "https://www.otterbox.com/")
        print(Otter_Box.name)
        print(Otter_Box.description)
        print(Otter_Box.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Otter_Box.name)
        f.write("\n")
        f.write(Otter_Box.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "old navy":
        Old_Navy = Website("Old Navy", "Lifestyle and clothing brand", "https://oldnavy.gapcanada.ca/")
        print(Old_Navy.name)
        print(Old_Navy.description)
        print(Old_Navy.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Old_Navy.name)
        f.write("\n")
        f.write(Old_Navy.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "polaris":
        Polaris = Website("Polaris", "All terrain and snowmobile manufacturer", "https://www.polaris.com/en-ca/")
        print(Polaris.name)
        print(Polaris.description)
        print(Polaris.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Polaris.name)
        f.write("\n")
        f.write(Polaris.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "ski-doo":
        Ski_doo = Website("Ski-doo", "Snowmobile manufacturer", "https://www.ski-doo.com/ca/en/")
        print(Ski_doo.name)
        print(Ski_doo.description)
        print(Ski_doo.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Ski_doo.name)
        f.write("\n")
        f.write(Ski_doo.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "sea-doo":
        Sea_doo = Website("Sea-doo", "Watercraft manufacturer", "https://www.sea-doo.com/ca/en/")
        print(Sea_doo.name)
        print(Sea_doo.description)
        print(Sea_doo.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Sea_doo.name)
        f.write("\n")
        f.write(Sea_doo.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "can-am":
        Can_am = Website("Can-Am", "All terrain manufacturer", "https://can-am.brp.com/")
        print(Can_am.name)
        print(Can_am.description)
        print(Can_am.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Can_am.name)
        f.write("\n")
        f.write(Can_am.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "yamaha":
        Yamaha = Website("Yamaha", "All terrain, Snowmobile and Music manufacturer", "https://www.yamaha-motor.ca/en/homepage and https://ca.yamaha.com/en/lang.html")
        print(Yamaha.name)
        print(Yamaha.description)
        print(Yamaha.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Yamaha.name)
        f.write("\n")
        f.write(Yamaha.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "arctic cat":
        Arctic_Cat = Website("Arctic Cat", "All terrain and Snowmobile manufacturer", "https://arcticcat.txtsv.com/")
        print(Arctic_Cat.name)
        print(Arctic_Cat.description)
        print(Arctic_Cat.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Arctic_Cat.name)
        f.write("\n")
        f.write(Arctic_Cat.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "509":
        Five_O_Nine = Website("509", "Snowmobile clothing manufacturer", "https://ride509.com/")
        print(Five_O_Nine.name)
        print(Five_O_Nine.description)
        print(Five_O_Nine.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Five_O_Nine.name)
        f.write("\n")
        f.write(Five_O_Nine.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "chevy":
        Chevy = Website("Chevy", "Automotive manufacturer", "https://www.chevrolet.com/")
        print(Chevy.name)
        print(Chevy.description)
        print(Chevy.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Chevy.name)
        f.write("\n")
        f.write(Chevy.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "ford":
        Ford = Website("Ford", "Automotive manufacturer", "https://www.ford.ca/")
        print(Ford.name)
        print(Ford.description)
        print(Ford.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Ford.name)
        f.write("\n")
        f.write(Ford.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "dodge":
        Dodge = Website("Dodge", "Automotive manufacturer", "https://www.dodge.ca/en")
        print(Dodge.name)
        print(Dodge.description)
        print(Dodge.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Dodge.name)
        f.write("\n")
        f.write(Dodge.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "toyota":
        Toyota = Website("Toyota", "Automotive manufacturer", "https://www.toyota.ca/toyota/en/")
        print(Toyota.name)
        print(Toyota.description)
        print(Toyota.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Toyota.name)
        f.write("\n")
        f.write(Toyota.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "honda":
        Honda = Website("Honda", "Automotive manufacturer", "https://www.honda.ca/")
        print(Honda.name)
        print(Honda.description)
        print(Honda.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Honda.name)
        f.write("\n")
        f.write(Honda.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "nissan":
        Nissan = Website("Nissan", "Automotive manufacturer", "https://www.nissan.ca/")
        print(Nissan.name)
        print(Nissan.description)
        print(Nissan.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Nissan.name)
        f.write("\n")
        f.write(Nissan.url)
        f.write("\n")
        f.write("\n")
        f.close
    elif user_input == "kia":
        Kia = Website("Kia", "Automotive manufacturer", "https://www.kia.ca/home")
        print(Kia.name)
        print(Kia.description)
        print(Kia.url)
        print("\n")
        f = open("history.txt", "a+")
        f.write(Kia.name)
        f.write("\n")
        f.write(Kia.url)
        f.write("\n")
        f.write("\n")
        f.close
    #The user can access the list of websites
    elif user_input == "list":
        lis.list()
    #If the user wants they can
    elif user_input == "title":
        lis.title()
    elif user_input == "h":
        f = open("history.txt", "r")
        print(f.read())
    #Quit option to leave the browser
    elif user_input == "quit":
        print("Thank you for using the browser")
        a = 2
    elif user_input == "help":
        print('''
                Welcome to the help section of Bew.

If you need a list of websites avalible you can use the command: list 
(TYPE THE COMMAND EXACTLY OR ELSE IT WILL NOT WORK!!)

If you already searched a site and you want to recover it you can type the command: h
(TYPE THE COMMAND EXACTLY OR ELSE IT WILL NOT WORK!!)
        ''')
    #Any errore the user makes will print a message to help
    else:
        print('''
USE LOWER CASE AND PROPER SPELLING.
If spelling is an issue Bew also recommends the command 'list' to find the site you desire.

IF ALL IS CORRECT THE WEBSITE IS NOT AVALIBLE
We at Bew appologize about the inconvenience.''')
        print("\n")
